### ISSUE TITLE
make wrong

### ISSUE THREAD

**Issue by airstring** [bbusse/hbase-exporter#1]
There is something wrong.Could you help me? Thanks!

`[root@node-01 hbase-exporter]# make 
Generating Python Protobuf bindings from HBase source
mkdir /opt/tmp/hbase-exporter/hbase-protobuf-python
git clone --depth 1 https://github.com/apache/hbase /tmp/hbase
Cloning into '/tmp/hbase'...
remote: Enumerating objects: 6089, done.
remote: Counting objects: 100% (6089/6089), done.
remote: Compressing objects: 100% (5157/5157), done.
remote: Total 6089 (delta 1861), reused 1657 (delta 498), pack-reused 0
Receiving objects: 100% (6089/6089), 17.58 MiB | 23.00 KiB/s, done.
Resolving deltas: 100% (1861/1861), done.
cd /tmp/hbase/hbase-protocol-shaded/src/main/protobuf; \
protoc -I=/usr/local/include/ --proto_path=. --python_out=/opt/tmp/hbase-exporter/hbase-protobuf-python *.proto
cd /tmp/hbase/hbase-protocol-shaded/src/main/protobuf; \
protoc -I=/usr/local/include/ --proto_path=. --python_out=/opt/tmp/hbase-exporter/hbase-protobuf-python client/*.proto
cd /tmp/hbase/hbase-protocol-shaded/src/main/protobuf; \
protoc -I=/usr/local/include/ --proto_path=. --python_out=/opt/tmp/hbase-exporter/hbase-protobuf-python server/*.proto
google/protobuf/any.proto: File not found.
server/Procedure.proto: Import "google/protobuf/any.proto" was not found or had errors.
server/Procedure.proto:61:12: "google.protobuf.Any" is not defined.
make: *** [all] Error 1
`

**Comment by bbusse** [comment]
Depending on the distribution you are using, you might need additional packages, like 'libprotobuf-dev' on Debian/Ubuntu or 'protobuf-devel' on Red Hat based distributions like RHEL/CentOS/Fedora. What distribution are you running this on?

**Comment by bbusse** [comment]
README updated
